## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - 1.0.0
notifications:
  email: false
git:
  depth: 99999999

script:
  - julia -e 'using Pkg; pkg"build AcausalNets"; pkg"add QuantumInformation"; pkg"add Test"; pkg"test AcausalNets"'
