## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - 1.0.0
notifications:
  email: false
git:
  depth: 99999999

script:
  # install unstable dependency
  - julia -e 'using Pkg; Pkg.clone("https://github.com/ZKSI/QI.jl")'
  # proceed with regular building process
  - julia -e 'using Pkg; Pkg.build("AcausalNets"); Pkg.add("QI"); Pkg.add("Test"); Pkg.test("AcausalNets"; coverage=true)'
